default: true
MD007: # Unordered list indentation
  indent: 4
MD013: false # Line length
MD029: # Ordered list item prefix
  style: one_or_ordered
MD033: # Inline HTML
  allowed_elements:
  - a
MD036: false # Emphasis used instead of a header
MD040: false # Fenced code blocks should have a language specified
MD041: false # First line in file should be a top level header
no-hard-tabs: true 
whitespace: true 
