module.exports = {
    docs: [
      {
        type: "doc",
        id: "installation",
      },
      {
        type: "category",
        label: "Getting Started",
        collapsed: true,
        items: [
            "getting-started/how-do-i-connect",
            "getting-started/box-basics",
            "getting-started/faqs"
          ],
      },
      {
        type: "category",
        label: "Applications",
        collapsed: true,
        items: [
            "applications/autodl",
            "applications/bazarr",
            "applications/btsync",
            "applications/couchpotato",
            "applications/csf",
            "applications/deluge",
            "applications/duckdns",
            "applications/emby",
            "applications/ffmpeg",
            "applications/flood",
            "applications/headphones",
            "applications/jackett",
            "applications/jellyfin",
            "applications/letsencrypt",
            "applications/lidarr",
            "applications/lounge",
            "applications/mango",
            "applications/medusa",
            "applications/netdata",
            "applications/nextcloud",
            "applications/nginx",
            "applications/nzbget",
            "applications/nzbhydra",
            "applications/ombi",
            "applications/panel",
            "applications/plex",
            "applications/pyload",
            "applications/qbittorrent",
            "applications/quassel",
            "applications/quota",
            "applications/radarr",
            "applications/rapidleech",
            "applications/rclone",
            "applications/rtorrent",
            "applications/rutorrent",
            "applications/sabnzbd",
            "applications/shellinabox",
            "applications/sickchill",
            "applications/sickgear",
            "applications/sonarr",
            "applications/sonarrv3",
            "applications/subsonic",
            "applications/syncthing",
            "applications/tautulli",
            "applications/transmission",
            "applications/vsftpd",
            "applications/wireguard",
            "applications/webmin",
            "applications/x2go",
            "applications/xmr-stak",
            "applications/znc"
          ],
      },
      {
        type: "category",
        label: "Guides",
        collapsed: true,
        items: [
            "guides/dist-upgrade",
            "guides/troubleshooting"
          ],
      },
      {
        type: "category",
        label: "Helper Scripts",
        collapsed: true,
        items: [
            "scripts/setdisk",
          ],
      },
    ],
  };
